<a href="https://colab.research.google.com/github/OjedaRocio/TP-Grupal-Laboratorio-2C-2026/blob/valen/TP_Grupal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio de Método Cuantitativos. FCE UBA-2C 2026


---


# TP-Grupal

**Integrantes**:

* *Ojeda Rocío, 921426*
* Zurita Fernandez Valentina, 921469
* *Uriarte Martinez Hilda Anabel, 921802*
*  *Aliaga Campos Tania Andrea, 921715*

**Repositorio:**
TP-Grupal-Laboratorio-2C-2026 ; **Dataset:** track_data_final.csv ; **Fuente:** https://www.kaggle.com/datasets/wardabilal/spotify-global-music-dataset-20092025?resource=download



---

**¿Es verdad que las canciones Globales se volvieron más cortas a lo largo del tiempo?**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 🤖 Declaración de Uso de IA en este Paso
*Con el fin de mantener la transparencia e integridad académica del proyecto, se detalla el uso de herramientas de Inteligencia Artificial para el desarrollo de esta sección:*

* **Herramienta utilizada**: Colab AI / Assistant (basado en Gemini).
* **Propósito**:  Diseño de un bloque de carga colaborativo dinámico entre integrantes.
* **Prompts:** *¿Qué pasa con la ruta del archivo si compartimos el notebook en GitHub con otra compañera?*

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Definimos las rutas posibles para cada integrante del equipo o entorno
RUTA_LOCAL_COLAB = '/content/track_data_final.csv'
RUTA_DRIVE_ROCIO = '/content/drive/MyDrive/track_data_final.csv'
#ACA DEBEN DE CAMBIAR EL LINK DIRECTO A SU DRIVE, DESDE ARCHIVOS ABREN DRIVE BUSCAN EL DATA Y EN LOS TRES PUNTOS COPIAR RUTA DE ACCESO.
RUTA_DRIVE_VALENTINA = '/content/drive/MyDrive/dataset_colab/archivo.csv'
RUTA_DRIVE_HILDA = '/content/drive/MyDrive/Compartido/track_data_final.csv'
RUTA_DRIVE_TANIA = '/content/drive/MyDrive/Compartido/track_data_final.csv'

# El código intenta elegir automáticamente la ruta que esté disponible en el entorno actual
if os.path.exists(RUTA_LOCAL_COLAB):
    ruta_activa = RUTA_LOCAL_COLAB
    print("Cargando archivo desde el almacenamiento local de Colab.")
elif os.path.exists(RUTA_DRIVE_ROCIO):
    ruta_activa = RUTA_DRIVE_ROCIO
    print("Cargando archivo desde el Drive de Rocío.")
elif os.path.exists(RUTA_DRIVE_VALENTINA):
    ruta_activa = RUTA_DRIVE_VALENTINA
    print("Cargando archivo desde el Drive de tu Valentina.")
elif os.path.exists(RUTA_DRIVE_HILDA):
    ruta_activa = RUTA_DRIVE_HILDA
    print("Cargando archivo desde el Drive de tu Hilda.")
elif os.path.exists(RUTA_DRIVE_TANIA):
    ruta_activa = RUTA_DRIVE_TANIA
    print("Cargando archivo desde el Drive de tu Tania.")
else:
    # Ruta de respaldo por si acaso
    ruta_activa = RUTA_LOCAL_COLAB
    print("No se detectó el archivo en las rutas configuradas. Usando ruta por defecto local.")

# Cargamos el DataFrame final utilizando la ruta seleccionada automáticamente
df_spotify = pd.read_csv(ruta_activa)

Cargando archivo desde el Drive de tu Valentina.

#Paso 1: Exploracion inicial de datos


---


##Antes de realizar el análisis profundo, procedimos a cargar los datos de Spotify para evaluar las columnas disponibles, identificar la cantidad total de canciones que contiene, detectar posibles datos nulos y unificar criterios en los tipos de datos.

In [3]:
#Visualizamos todo el data que tenemos.
df_spotify

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8773,58VTP6KnZs12PcAj5rMJ4W,the fruits,1,65,209698,False,Paris Paloma,66.0,786890.0,[],48ssTnnFOCIP17sRaFNqu1,the fruits,2022-04-29,1,single
8774,2dRfUOeTVpr4V4PmmqGkpm,Dark World Theme (The Legend of Zelda),4,2,113143,False,Zelda,8.0,3263.0,[],0JJAfVZtn3EvZnXSQrpLSh,The Legend of Zelda,2023-08-19,7,album
8775,37F0uwRSrdzkBiuj0D5UHI,Reminder,4,81,218880,True,The Weeknd,94.0,113039308.0,[],2ODvWsOgouMbaA5xf0RkJe,Starboy,2016-11-25,18,album
8776,42qNWdLKCI41S4uzfamhFM,Duvet,1,84,203600,False,bôa,68.0,1188508.0,[],7sGYAV0xv7ZfAMzIpMl8m1,Twilight,2001-03-21,14,album
8777,7KZJnMtwu2s80jO5Frthap,So Much Better,4,33,261385,True,Eminem,88.0,104584370.0,"['rap', 'hip hop']",3vOgbDjgsZBAPwV2M3bNOj,The Marshall Mathers LP2,2013-11-05,16,album

In [4]:
#visualizamos los primeros 10 datos
df_spotify.head(10)

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album
5,7H0ya83CMmgFcOhw0UB6ow,Space Song,3,77,320466,False,Beach House,72.0,2803036.0,['dream pop'],194CqC2Zi0kUFEPWedb3qr,Depression Cherry,2015-08-28,9,album
6,41zXlQxzTi6cGAjpOXyLYH,idontwannabeyouanymore,2,78,203569,False,Billie Eilish,90.0,118692183.0,[],7fRrTyKvE4Skh93v97gtcU,dont smile at me,2017-12-22,9,single
7,13jRFAGT8qd6aBwtJySlUm,Allein Allein - BENNETT Remix,1,52,145977,False,Alok,76.0,11247155.0,"['brazilian bass', 'electronic', 'slap house',...",1WKoDELzbFRR6UWNGh50LO,Allein Allein (feat. FREY) [BENNETT Remix],2024-09-27,2,single
8,0N5zjRnf8AreOm95iSBXF4,Even My Dad Does Sometimes,15,50,228533,False,Ed Sheeran,88.0,122773292.0,['soft pop'],1xn54DMo2qIqBuMqHtUsFd,x (Deluxe Edition),2014-06-21,16,album
9,0qUcpOOna3kkrwfqky85e1,Eyes Blue Like The Atlantic (feat. Subvrbs),1,63,154599,False,Sista Prod,48.0,68226.0,[],5UYjxc4HIYeesKS0WJlhEI,Eyes Blue Like The Atlantic (feat. Subvrbs),2020-07-20,1,single

In [5]:
#visualizamos los ultimos 3 datos.
df_spotify.tail(10)

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
8768,2z71jdeVcC782NgsYZ6N8q,Paranoid (2012 Remaster),2,66,166693,False,Black Sabbath,75.0,9781962.0,"['metal', 'heavy metal', 'rock', 'stoner rock'...",7LGVdC9fFwgWYaIrZwsSv6,Paranoid,1970-09-18,8,album
8769,4y4spB9m0Q6026KfkAvy9Q,Lonely (with benny blanco),1,66,149297,True,Justin Bieber,91.0,85050158.0,[],3P5WIUJO0Ots1lQx09TOxk,Lonely (with benny blanco),2020-10-16,1,single
8770,6GFrELGVKBXRcrTNkwjSfF,Body And Mind,3,54,186672,False,girl in red,73.0,8771418.0,['bedroom pop'],69p42ovQdwmYPLUsAQpeNn,if i could make it go quiet,2021-04-30,11,album
8771,1gtflD7JVxpozNitZJp6xu,The Legend of Korra End Credits,25,34,30706,False,Jeremy Zuckerman,44.0,23565.0,[],2LOLFpqUHrlQPAiqzLVJBN,The Legend of Korra: Original Music From Book One,2013-07-16,26,album
8772,2d8JP84HNLKhmd6IYOoupQ,Trap Queen,1,77,222093,True,Fetty Wap,70.0,5124117.0,[],2gKQvajkEEaDtkqJ8FJ4uw,Fetty Wap (Deluxe),2015-09-25,20,album
8773,58VTP6KnZs12PcAj5rMJ4W,the fruits,1,65,209698,False,Paris Paloma,66.0,786890.0,[],48ssTnnFOCIP17sRaFNqu1,the fruits,2022-04-29,1,single
8774,2dRfUOeTVpr4V4PmmqGkpm,Dark World Theme (The Legend of Zelda),4,2,113143,False,Zelda,8.0,3263.0,[],0JJAfVZtn3EvZnXSQrpLSh,The Legend of Zelda,2023-08-19,7,album
8775,37F0uwRSrdzkBiuj0D5UHI,Reminder,4,81,218880,True,The Weeknd,94.0,113039308.0,[],2ODvWsOgouMbaA5xf0RkJe,Starboy,2016-11-25,18,album
8776,42qNWdLKCI41S4uzfamhFM,Duvet,1,84,203600,False,bôa,68.0,1188508.0,[],7sGYAV0xv7ZfAMzIpMl8m1,Twilight,2001-03-21,14,album
8777,7KZJnMtwu2s80jO5Frthap,So Much Better,4,33,261385,True,Eminem,88.0,104584370.0,"['rap', 'hip hop']",3vOgbDjgsZBAPwV2M3bNOj,The Marshall Mathers LP2,2013-11-05,16,album

In [6]:
#Comenzamos visualizando las columnas y filas del data
print("---Columnas, Filas & Tipos de datos.---")
print("")

print("Filas y Columnas:", df_spotify.shape)
print("")

df_spotify.info()

---Columnas, Filas & Tipos de datos.---

Filas y Columnas: (8778, 15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8778 entries, 0 to 8777
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8778 non-null   object
 1   track_name          8776 non-null   object
 2   track_number        8778 non-null   int64
 3   track_popularity    8778 non-null   int64
 4   track_duration_ms   8778 non-null   int64
 5   explicit            8778 non-null   bool
 6   artist_name         8774 non-null   object
 7   artist_popularity   8774 non-null   float64
 8   artist_followers    8774 non-null   float64
 9   artist_genres       8774 non-null   object
 10  album_id            8778 non-null   object
 11  album_name          8776 non-null   object
 12  album_release_date  8778 non-null   object
 13  album_total_tracks  8778 non-null   int64
 14  album_type          8778 non-null   object
dtypes: bool(1), float64(2), int64(4), object(8)
memory usage: 968.8+ KB

In [7]:
# Cuenta los valores nulos en cada columna
df_spotify.isnull().sum()

track_id              0
track_name            2
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           4
artist_popularity     4
artist_followers      4
artist_genres         4
album_id              0
album_name            2
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

# **Limpieza:**
aseguramos que las columnas que necesitamos (**artist_name** y **track_name**) queden sin un solo valor nulo antes de agrupar o graficar

In [8]:
# 1. Eliminar filas donde falte el Nombre de la Canción o el Nombre del Artista
df_spotify = df_spotify.dropna(subset=["track_name", "artist_name"]).reset_index(drop=True)

# 2. Verificar que esas dos columnas clave hayan quedado en 0 nulos
print("--- Verificación de Nulos en Columnas Clave ---")
print("Nulos en 'track_name':", df_spotify["track_name"].isnull().sum())
print("Nulos en 'artist_name':", df_spotify["artist_name"].isnull().sum())

# 3. Ver cuántas filas quedaron en total tras el descarte
print("\nCantidad total de filas procesadas:", len(df_spotify))

--- Verificación de Nulos en Columnas Clave ---
Nulos en 'track_name': 0
Nulos en 'artist_name': 0

Cantidad total de filas procesadas: 8772

# **Hallazgos:**
La columna **"album_release_date"** se encuentra como cadena de *texto*, necesitamos modificarla como **INT** para poder trabajar evoluciones temporales. Verificamos la forma de las fechas en el dataset original y corroboramos si existen registros con formatos diferentes a AAAA-MM-DD **priorizando el dato del AÑO (AAAA).**
Asumir que todas las entradas tienen día y mes puede generar la pérdida involuntaria de datos.

Se **analiza** la distribución de **la longitud** de las cadenas de texto para encontrar inconsistencias de origen antes de estructurar la columna definitiva del Año de lanzamiento.

In [11]:
# Contar cuántos caracteres tiene el texto de cada celda
# - 10 caracteres -> "AAAA-MM-DD" (Año-Mes-Día)
# - 7 caracteres  -> "AAAA-MM" (Año-Mes)
# - 4 caracteres  -> "AAAA" (Solo año)
conteo_formatos = df_spotify["album_release_date"].astype(str).str.len().value_counts()

print("--- Distribución de longitud del texto en 'album_release_date' ---")
print(conteo_formatos)

--- Distribución de longitud del texto en 'album_release_date' ---
album_release_date
10    8573
4      196
7        3
Name: count, dtype: int64

In [13]:
# Filtrar y mostrar las filas que tienen solo 4 caracteres en la fecha
solo_anios = df_spotify[df_spotify["album_release_date"].astype(str).str.len() == 4]

# Mostrar las primeras 5 filas para comprobar su contenido
display(solo_anios[["track_name", "artist_name", "album_release_date"]].head())

       track_name    artist_name album_release_date
27   Did It Again        Shakira               2009
49         9 to 5   Dolly Parton               1980
67  My Bubble Gum       Rasheeda               2007
87            Run    Leona Lewis               2007
92        Popular  The Veronicas               2005


# **Hallazgos:**
 Columna **"track_duration_ms"** numero entero en *milisegundos*, queremos pasarlos a **minutos** para que sea mas facil leer y utilizar los datos a la hora de compararlos.

### 🤖 Declaración de Uso de IA en este Paso


* **Herramienta utilizada**: chat_gpt proyect
* **Propósito**: transformar fechas y minutos
* **Prompts:** *Como analista de datos senior de la indrustria musical, armate un codigo para poder extraer solo el año en formato entero (int) de la columna de fechas del dataset track_data_final, rescatando los años de 4 digitos. Y ademas un codigo para poder visualizar esto junto con el cambio de minutos de reproduccion.*

In [14]:
# 1. Insertar el ID único numérico
df_spotify.insert(0, "ID canción", range(1, len(df_spotify) + 1))

# 2. Convertir la duración de milisegundos a minutos
df_spotify["duracion_minutos"] = (
    pd.to_numeric(df_spotify["track_duration_ms"], errors="coerce") / 60000
).round(2)

# 3. EXTRAER SOLO EL AÑO COMO ENTERO (INT):
# Extrae los 4 dígitos (AAAA) de la columna de texto original y los transforma a número entero (int)
df_spotify["album_release_year"] = (
    df_spotify["album_release_date"]
    .astype(str)
    .str.extract(r'(\d{4})')[0]
    .astype(int)
)

# 4. Cambiar los nombres de las columnas para facilitar su lectura
df = df_spotify.rename(columns={
    "track_id": "ID Spotify",
    "track_name": "Nombre de la canción",
    "track_number": "Número de pista",
    "track_popularity": "Popularidad de la canción",
    "track_duration_ms": "Duración original (ms)",
    "explicit": "Contenido explícito",
    "artist_name": "Nombre del artista",
    "artist_popularity": "Popularidad del artista",
    "artist_followers": "Seguidores del artista",
    "artist_genres": "Géneros musicales",
    "album_id": "ID del álbum",
    "album_name": "Nombre del álbum",
    "album_release_date": "Fecha de lanzamiento original",
    "album_release_year": "Año de lanzamiento",
    "album_total_tracks": "Cantidad de canciones del álbum",
    "album_type": "Tipo de álbum",
    "duracion_minutos": "Duración (minutos)"
})

# Mostrar algunas filas para comprobar el resultado
display(df.head())

# Guardar el dataset con los cambios
df.to_csv("track_data_final_legible.csv", index=False, encoding="utf-8-sig")

,ID canción,ID Spotify,Nombre de la canción,Número de pista,Popularidad de la canción,Duración original (ms),Contenido explícito,Nombre del artista,Popularidad del artista,Seguidores del artista,Géneros musicales,ID del álbum,Nombre del álbum,Fecha de lanzamiento original,Cantidad de canciones del álbum,Tipo de álbum,Duración (minutos),Año de lanzamiento
0,1,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation,3.55,2009
1,2,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single,2.65,2023
2,3,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album,3.76,2021
3,4,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album,2.64,2021
4,5,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album,4.45,2010

In [15]:
# 1. Comprobar la cantidad de valores nulos en la nueva columna
nulos_año = df["Año de lanzamiento"].isnull().sum()
print("Cantidad de nulos en 'Año de lanzamiento':", nulos_año)

# 2. Verificar el tipo de dato (debe ser int64)
print("Tipo de dato de la columna:", df["Año de lanzamiento"].dtype)

# 3. Ver un resumen del rango de años rescatados
print("Año mínimo:", df["Año de lanzamiento"].min())
print("Año máximo:", df["Año de lanzamiento"].max())

Cantidad de nulos en 'Año de lanzamiento': 0
Tipo de dato de la columna: int64
Año mínimo: 1952
Año máximo: 2025

# **Hallazgos**:
Al buscar **Año minimo** encontramos un limite **atipico** de **1952**, el cual debemos comprobar para que *no distorcione* la escala cronológica de los futuros gráficos evolutivos.
Verificar exactamente cuántas canciones hay en cada año y corroborar este posible **hueco temporal**

In [16]:
# Contar la cantidad de canciones por año y ordenarlos cronológicamente
conteo_por_año = df["Año de lanzamiento"].value_counts().sort_index()

print("--- DISTRIBUCIÓN DE CANCIONES POR AÑO ---")
print(conteo_por_año)

--- DISTRIBUCIÓN DE CANCIONES POR AÑO ---
Año de lanzamiento
1952      1
1958      1
1959      5
1960      1
1962      5
       ...
2021    448
2022    475
2023    525
2024    658
2025    768
Name: count, Length: 68, dtype: int64

In [17]:
# 1. Contar canciones por año
conteo_anios = df["Año de lanzamiento"].value_counts().sort_index()

# 2. Filtrar solo los años con 100 canciones o más
anios_representativos = conteo_anios[conteo_anios >= 100]

print("--- AÑOS CON 100 O MÁS CANCIONES ---")
print(anios_representativos)
print("\nPrimer año representativo en el dataset:", anios_representativos.index.min())

--- AÑOS CON 100 O MÁS CANCIONES ---
Año de lanzamiento
2003    103
2007    110
2008    103
2009    158
2010    251
2011    270
2012    335
2013    316
2014    352
2015    405
2016    388
2017    473
2018    534
2019    500
2020    494
2021    448
2022    475
2023    525
2024    658
2025    768
Name: count, dtype: int64

Primer año representativo en el dataset: 2003

In [18]:
# 1. Aplicar el filtro definitivo (>= 2003) sobre el mismo DataFrame
df = df[df["Año de lanzamiento"] >= 2003].copy()

# 2. Configurar Pandas para ver todas las columnas prolijas
pd.set_option('display.max_columns', None)

# 3. Mostrar el resumen del dataset filtrado
print("--- RESUMEN DEL DATASET LIMPIO Y FILTRADO ---")
print("Total de filas y columnas:", df.shape)
print("Cantidad de nulos en 'Año de lanzamiento':", df["Año de lanzamiento"].isnull().sum())
print("Rango de años representativo:", df["Año de lanzamiento"].min(), "-", df["Año de lanzamiento"].max())

# Visualizar las primeras 5 filas
display(df.head())

--- RESUMEN DEL DATASET LIMPIO Y FILTRADO ---
Total de filas y columnas: (7911, 18)
Cantidad de nulos en 'Año de lanzamiento': 0
Rango de años representativo: 2003 - 2025

,ID canción,ID Spotify,Nombre de la canción,Número de pista,Popularidad de la canción,Duración original (ms),Contenido explícito,Nombre del artista,Popularidad del artista,Seguidores del artista,Géneros musicales,ID del álbum,Nombre del álbum,Fecha de lanzamiento original,Cantidad de canciones del álbum,Tipo de álbum,Duración (minutos),Año de lanzamiento
0,1,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation,3.55,2009
1,2,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single,2.65,2023
2,3,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album,3.76,2021
3,4,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album,2.64,2021
4,5,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album,4.45,2010

In [19]:
# 1. Contar cuántos duplicados exactos hay por el ID único de Spotify
duplicados_id = df["ID Spotify"].duplicated().sum()

# 2. Contar cuántas canciones repetidas hay (mismo nombre de canción y mismo artista)
duplicados_cancion = df.duplicated(subset=["Nombre de la canción", "Nombre del artista"]).sum()

print("--- RESULTADO DE LA AUDITORÍA DE DUPLICADOS ---")
print("1. Registros duplicados por ID Spotify:", duplicados_id)
print("2. Canciones repetidas (Mismo Nombre + Mismo Artista):", duplicados_cancion)

--- RESULTADO DE LA AUDITORÍA DE DUPLICADOS ---
1. Registros duplicados por ID Spotify: 0
2. Canciones repetidas (Mismo Nombre + Mismo Artista): 812

In [21]:
# Filtrar y mostrar las filas duplicadas agrupadas para inspeccionarlas
filas_duplicadas = df[df.duplicated(subset=["Nombre de la canción", "Nombre del artista"], keep=False)].sort_values(by=["Nombre del artista", "Nombre de la canción"])

print("\n--- EJEMPLOS DE CANCIONES REPETIDAS EN EL DATASET ---")
display(filas_duplicadas[["Nombre de la canción", "Nombre del artista", "Nombre del álbum", "Año de lanzamiento", "Duración (minutos)"]].head(12))

--- EJEMPLOS DE CANCIONES REPETIDAS EN EL DATASET ---

,Nombre de la canción,Nombre del artista,Nombre del álbum,Año de lanzamiento,Duración (minutos)
1449,Mood (feat. iann dior),24kGoldn,El Dorado,2021,2.34
7437,Mood (feat. iann dior),24kGoldn,Mood (feat. iann dior),2020,2.34
2905,Candy Shop,50 Cent,The Massacre,2005,3.49
4559,Candy Shop,50 Cent,The Massacre,2005,3.48
110,In Da Club,50 Cent,00s Middle School Dance,2019,3.22
2460,In Da Club,50 Cent,Get Rich Or Die Tryin',2003,3.22
3525,In Da Club,50 Cent,Get Rich Or Die Tryin',2003,3.22
702,Sail,AWOLNATION,Megalithic Symphony,2011,4.32
4731,Sail,AWOLNATION,Megalithic Symphony Deluxe,2011,4.32
4498,Aquamarine,Addison Rae,Aquamarine,2024,2.71
4608,Aquamarine,Addison Rae,Addison,2025,2.71
1322,Diet Pepsi,Addison Rae,Addison,2025,2.83

In [22]:
# Eliminar las canciones repetidas dejando el primer registro
df = df.drop_duplicates(subset=["Nombre de la canción", "Nombre del artista"], keep="first").reset_index(drop=True)

# Comprobar que ya no quedan duplicados
print("Cantidad total de canciones únicas listas para analizar:", len(df))
print("Duplicados restantes:", df.duplicated(subset=["Nombre de la canción", "Nombre del artista"]).sum())

Cantidad total de canciones únicas listas para analizar: 7099
Duplicados restantes: 0