<a href="https://colab.research.google.com/github/OjedaRocio/TP-Grupal-Laboratorio-2C-2026/blob/main/TP_Grupal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio de Método Cuantitativos. FCE UBA-2C 2026


---


# TP-Grupal

**Integrantes**:

* *Ojeda Rocío, 921426*
* Zurita Fernandez Valentina, 921469
* *Uriarte Martinez Hilda Anabel, 921802*
*  *Aliaga Campos Tania Andrea, 921715*

**Repositorio:**
TP-Grupal-Laboratorio-2C-2026 ; **Dataset:** track_data_final.csv ; **Fuente:** https://www.kaggle.com/datasets/wardabilal/spotify-global-music-dataset-20092025?resource=download



---

**¿Es verdad que las canciones Globales se volvieron más cortas a lo largo del tiempo?**

In [89]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 🤖 Declaración de Uso de IA en este Paso
*Con el fin de mantener la transparencia e integridad académica del proyecto, se detalla el uso de herramientas de Inteligencia Artificial para el desarrollo de esta sección:*

* **Herramienta utilizada**: Colab AI / Assistant (basado en Gemini).
* **Propósito**:  Diseño de un bloque de carga colaborativo dinámico entre integrantes.
* **Prompts:** *¿Qué pasa con la ruta del archivo si compartimos el notebook en GitHub con otra compañera?*

In [90]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Definimos las rutas posibles para cada integrante del equipo o entorno
RUTA_LOCAL_COLAB = '/content/track_data_final.csv'
RUTA_DRIVE_ROCIO = '/content/drive/MyDrive/track_data_final.csv'
#ACA DEBEN DE CAMBIAR EL LINK DIRECTO A SU DRIVE, DESDE ARCHIVOS ABREN DRIVE BUSCAN EL DATA Y EN LOS TRES PUNTOS COPIAR RUTA DE ACCESO.
RUTA_DRIVE_VALENTINA = '/content/drive/MyDrive/Compartido/track_data_final.csv'
RUTA_DRIVE_HILDA = '/content/drive/MyDrive/Compartido/track_data_final.csv'
RUTA_DRIVE_TANIA = '/content/drive/MyDrive/Compartido/track_data_final.csv'

# El código intenta elegir automáticamente la ruta que esté disponible en el entorno actual
if os.path.exists(RUTA_LOCAL_COLAB):
    ruta_activa = RUTA_LOCAL_COLAB
    print("Cargando archivo desde el almacenamiento local de Colab.")
elif os.path.exists(RUTA_DRIVE_ROCIO):
    ruta_activa = RUTA_DRIVE_ROCIO
    print("Cargando archivo desde el Drive de Rocío.")
elif os.path.exists(RUTA_DRIVE_VALENTINA):
    ruta_activa = RUTA_DRIVE_VALENTINA
    print("Cargando archivo desde el Drive de tu Valentina.")
elif os.path.exists(RUTA_DRIVE_HILDA):
    ruta_activa = RUTA_DRIVE_HILDA
    print("Cargando archivo desde el Drive de tu Hilda.")
elif os.path.exists(RUTA_DRIVE_TANIA):
    ruta_activa = RUTA_DRIVE_TANIA
    print("Cargando archivo desde el Drive de tu Tania.")
else:
    # Ruta de respaldo por si acaso
    ruta_activa = RUTA_LOCAL_COLAB
    print("No se detectó el archivo en las rutas configuradas. Usando ruta por defecto local.")

# Cargamos el DataFrame final utilizando la ruta seleccionada automáticamente
df_spotify = pd.read_csv(ruta_activa)

Cargando archivo desde el Drive de Rocío.

#Paso 1:Exploracion inicial de datos


---


##Antes de realizar el análisis profundo, procedimos a cargar los datos de Spotify para evaluar las columnas disponibles, identificar la cantidad total de canciones que contiene, detectar posibles datos nulos y unificar criterios en los tipos de datos.

In [91]:
#Visualizamos todo el data que tenemos.
df_spotify

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8773,58VTP6KnZs12PcAj5rMJ4W,the fruits,1,65,209698,False,Paris Paloma,66.0,786890.0,[],48ssTnnFOCIP17sRaFNqu1,the fruits,2022-04-29,1,single
8774,2dRfUOeTVpr4V4PmmqGkpm,Dark World Theme (The Legend of Zelda),4,2,113143,False,Zelda,8.0,3263.0,[],0JJAfVZtn3EvZnXSQrpLSh,The Legend of Zelda,2023-08-19,7,album
8775,37F0uwRSrdzkBiuj0D5UHI,Reminder,4,81,218880,True,The Weeknd,94.0,113039308.0,[],2ODvWsOgouMbaA5xf0RkJe,Starboy,2016-11-25,18,album
8776,42qNWdLKCI41S4uzfamhFM,Duvet,1,84,203600,False,bôa,68.0,1188508.0,[],7sGYAV0xv7ZfAMzIpMl8m1,Twilight,2001-03-21,14,album
8777,7KZJnMtwu2s80jO5Frthap,So Much Better,4,33,261385,True,Eminem,88.0,104584370.0,"['rap', 'hip hop']",3vOgbDjgsZBAPwV2M3bNOj,The Marshall Mathers LP2,2013-11-05,16,album

In [92]:
#visualizamos los ultimos 3 datos.
df_spotify.tail(3)

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
8775,37F0uwRSrdzkBiuj0D5UHI,Reminder,4,81,218880,True,The Weeknd,94.0,113039308.0,[],2ODvWsOgouMbaA5xf0RkJe,Starboy,2016-11-25,18,album
8776,42qNWdLKCI41S4uzfamhFM,Duvet,1,84,203600,False,bôa,68.0,1188508.0,[],7sGYAV0xv7ZfAMzIpMl8m1,Twilight,2001-03-21,14,album
8777,7KZJnMtwu2s80jO5Frthap,So Much Better,4,33,261385,True,Eminem,88.0,104584370.0,"['rap', 'hip hop']",3vOgbDjgsZBAPwV2M3bNOj,The Marshall Mathers LP2,2013-11-05,16,album

In [93]:
#Comenzamos visualizando las columnas y filas del data
print("---Columnas, Filas & Tipos de datos.---")
print("")

print("Filas y Columnas:", df_spotify.shape)
print("")

df_spotify.info()

---Columnas, Filas & Tipos de datos.---

Filas y Columnas: (8778, 15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8778 entries, 0 to 8777
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8778 non-null   object
 1   track_name          8776 non-null   object
 2   track_number        8778 non-null   int64
 3   track_popularity    8778 non-null   int64
 4   track_duration_ms   8778 non-null   int64
 5   explicit            8778 non-null   bool
 6   artist_name         8774 non-null   object
 7   artist_popularity   8774 non-null   float64
 8   artist_followers    8774 non-null   float64
 9   artist_genres       8774 non-null   object
 10  album_id            8778 non-null   object
 11  album_name          8776 non-null   object
 12  album_release_date  8778 non-null   object
 13  album_total_tracks  8778 non-null   int64
 14  album_type          8778 non-null   object
dtypes: bool(1), float64(2), int64(4), object(8)
memory usage: 968.8+ KB

### 🤖 Declaración de Uso de IA en este Paso


* **Herramienta utilizada**: chat_gpt proyect
* **Propósito**: transformar fechas y minutos
* **Prompts:** *Como analista de datos senior de la indrustria musical, armate un codigo para poder transformar los dias de cada fila en el formato de año-mes-dia del data set de track_data_final. Y ademas un codigo para poder visualizar esto junto con el cambio de minutos de reproduccion.*

In [94]:
#Hacemos unos cambios de y transformacion de datos
df_analisis = df_spotify.copy()

#Convertimos la duracion en minutos para una mejor lectura.
df_analisis["Duración_minutos"] = df_analisis["track_duration_ms"] / 60000.0

# Mostrar algunas canciones con su duración (corregido usando df_analisis y los nombres de columnas reales)
print(
    df_analisis[["track_name", "album_release_date",
                 "track_duration_ms", "Duración_minutos"]].head()
)

# Convertimos la fecha de lanzamiento
 #coerce, transforma las fechas invalidas en valores nulos, en lugar de interrumpr el codigo
df_analisis["album_release_date"] = pd.to_datetime(
    df_analisis["album_release_date"], errors="coerce"
)
# Creamos una columna con formato año-mes-día
df_analisis["fecha_lanzamiento"] = df_analisis["album_release_date"].dt.strftime("%Y-%m-%d")

# Visualizamos los cambios
print("Primeras fechas convertidas:")
print(df_analisis[["album_release_date", "fecha_lanzamiento"]].head())

print("\nCantidad de fechas inválidas:")
print(df_analisis["album_release_date"].isna().sum())

# 5. Guardar el dataset transformado (opcional)
df_analisis.to_csv("track_data_fechas.csv", index=False)

                            track_name album_release_date  track_duration_ms  \
0                                    3         2009-11-09             213173
1                               Clouds         2023-01-13             158760
2  Forever & Always (Taylor’s Version)         2021-04-09             225328
3            I Didn't Change My Number         2021-07-30             158463
4                             Man Down         2010-01-01             267013

   Duración_minutos
0          3.552883
1          2.646000
2          3.755467
3          2.641050
4          4.450217
Primeras fechas convertidas:
  album_release_date fecha_lanzamiento
0         2009-11-09        2009-11-09
1         2023-01-13        2023-01-13
2         2021-04-09        2021-04-09
3         2021-07-30        2021-07-30
4         2010-01-01        2010-01-01

Cantidad de fechas inválidas:
201

In [96]:
df_analisis

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,Duración_minutos,fecha_lanzamiento
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation,3.552883,2009-11-09
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single,2.646000,2023-01-13
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album,3.755467,2021-04-09
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album,2.641050,2021-07-30
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album,4.450217,2010-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8773,58VTP6KnZs12PcAj5rMJ4W,the fruits,1,65,209698,False,Paris Paloma,66.0,786890.0,[],48ssTnnFOCIP17sRaFNqu1,the fruits,2022-04-29,1,single,3.494967,2022-04-29
8774,2dRfUOeTVpr4V4PmmqGkpm,Dark World Theme (The Legend of Zelda),4,2,113143,False,Zelda,8.0,3263.0,[],0JJAfVZtn3EvZnXSQrpLSh,The Legend of Zelda,2023-08-19,7,album,1.885717,2023-08-19
8775,37F0uwRSrdzkBiuj0D5UHI,Reminder,4,81,218880,True,The Weeknd,94.0,113039308.0,[],2ODvWsOgouMbaA5xf0RkJe,Starboy,2016-11-25,18,album,3.648000,2016-11-25
8776,42qNWdLKCI41S4uzfamhFM,Duvet,1,84,203600,False,bôa,68.0,1188508.0,[],7sGYAV0xv7ZfAMzIpMl8m1,Twilight,2001-03-21,14,album,3.393333,2001-03-21
8777,7KZJnMtwu2s80jO5Frthap,So Much Better,4,33,261385,True,Eminem,88.0,104584370.0,"['rap', 'hip hop']",3vOgbDjgsZBAPwV2M3bNOj,The Marshall Mathers LP2,2013-11-05,16,album,4.356417,2013-11-05